/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthDataLockerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addHealthRecord"
      | "confidentialProtocolId"
      | "getEncryptedRecord"
      | "getRecordCount"
      | "makeRecordPublic"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RecordAdded" | "RecordMadePublic"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addHealthRecord",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeRecordPublic",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addHealthRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeRecordPublic",
    data: BytesLike
  ): Result;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    dataType: BigNumberish,
    timestamp: BigNumberish,
    encryptedValue: BytesLike,
    index: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    dataType: bigint,
    timestamp: bigint,
    encryptedValue: string,
    index: bigint
  ];
  export interface OutputObject {
    user: string;
    dataType: bigint;
    timestamp: bigint;
    encryptedValue: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordMadePublicEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    encryptedValue: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    index: bigint,
    encryptedValue: string
  ];
  export interface OutputObject {
    user: string;
    index: bigint;
    encryptedValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthDataLocker extends BaseContract {
  connect(runner?: ContractRunner | null): HealthDataLocker;
  waitForDeployment(): Promise<this>;

  interface: HealthDataLockerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addHealthRecord: TypedContractMethod<
    [
      dataType: BigNumberish,
      timestamp: BigNumberish,
      valueExt: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedRecord: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[bigint, bigint, string, boolean]],
    "view"
  >;

  getRecordCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  makeRecordPublic: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addHealthRecord"
  ): TypedContractMethod<
    [
      dataType: BigNumberish,
      timestamp: BigNumberish,
      valueExt: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedRecord"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[bigint, bigint, string, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "makeRecordPublic"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;
  getEvent(
    key: "RecordMadePublic"
  ): TypedContractEvent<
    RecordMadePublicEvent.InputTuple,
    RecordMadePublicEvent.OutputTuple,
    RecordMadePublicEvent.OutputObject
  >;

  filters: {
    "RecordAdded(address,uint32,uint256,bytes32,uint256)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;

    "RecordMadePublic(address,uint256,bytes32)": TypedContractEvent<
      RecordMadePublicEvent.InputTuple,
      RecordMadePublicEvent.OutputTuple,
      RecordMadePublicEvent.OutputObject
    >;
    RecordMadePublic: TypedContractEvent<
      RecordMadePublicEvent.InputTuple,
      RecordMadePublicEvent.OutputTuple,
      RecordMadePublicEvent.OutputObject
    >;
  };
}
